Repository rust-lang/rust-bindgen, pull requests merged in 2018-07, with the labels that each got.

#1346 ir: Don't assume wchar is 2 bytes.
  bindgen-integration/cpp/Test.h
  src/codegen/mod.rs
  src/ir/context.rs
  src/ir/int.rs
  src/ir/layout.rs
Labels: S-awaiting-merge

#1347 Regenerates the BSD3 License so GitHub recognises it
  LICENSE
Labels: S-awaiting-review

#1348 Track Rust target features with declaration macro
  src/features.rs
Labels: S-tests-failed

#1354 Improve error message when libclang fails
  src/ir/context.rs
Labels: S-awaiting-review

#1356 Quote regexes in test headers
  tests/headers/anon_enum.hpp
  tests/headers/anon_enum_trait.hpp
  tests/headers/anon_enum_whitelist.h
  tests/headers/anon_union.hpp
  tests/headers/anon_union_1_0.hpp
  tests/headers/bitfield-enum-basic.hpp
  tests/headers/bitfield_align_2.h
  tests/headers/class_with_inner_struct.hpp
  tests/headers/class_with_inner_struct_1_0.hpp
  tests/headers/const_enum_unnamed.hpp
  tests/headers/constant-evaluate.h
  tests/headers/constify-enum.h
  tests/headers/constify-module-enums-types.hpp
  tests/headers/enum.h
  tests/headers/enum_alias.hpp
  tests/headers/enum_and_vtable_mangling.hpp
  tests/headers/enum_dupe.h
  tests/headers/enum_explicit_type.hpp
  tests/headers/enum_in_template_with_typedef.hpp
  tests/headers/enum_negative.h
  tests/headers/enum_packed.h
  tests/headers/forward-enum-decl.hpp
  tests/headers/func_ptr_in_struct.h
  tests/headers/issue-372.hpp
  tests/headers/issue-410.hpp
  tests/headers/issue-493.hpp
  tests/headers/issue-493_1_0.hpp
  tests/headers/issue-569-non-type-template-params-causing-layout-test-failures.hpp
  tests/headers/issue-888-enum-var-decl-jump.hpp
  tests/headers/jsval_layout_opaque.hpp
  tests/headers/jsval_layout_opaque_1_0.hpp
  tests/headers/layout_array_too_long.h
  tests/headers/layout_cmdline_token.h
  tests/headers/layout_eth_conf.h
  tests/headers/layout_eth_conf_1_0.h
  tests/headers/layout_large_align_field.h
  tests/headers/no-recursive-whitelisting.h
  tests/headers/no-std.h
  tests/headers/nsStyleAutoArray.hpp
  tests/headers/opaque-tracing.hpp
  tests/headers/overflowed_enum.hpp
  tests/headers/prepend-enum-constified-variant.h
  tests/headers/short-enums.hpp
  tests/headers/struct_typedef.h
  tests/headers/struct_typedef_ns.hpp
  tests/headers/weird_bitfields.hpp
Labels: S-awaiting-review

#1355 Use associated constants for rust enums when available
  src/codegen/mod.rs
  tests/expectations/tests/anon_enum_trait.rs
  tests/expectations/tests/anon_union.rs
  tests/expectations/tests/constify-enum.rs
  tests/expectations/tests/enum_dupe.rs
  tests/expectations/tests/enum_in_template_with_typedef.rs
  tests/expectations/tests/issue-1198-alias-rust-enum.rs
  tests/expectations/tests/prepend-enum-constified-variant.rs
Labels: S-awaiting-review

#1351 select cpp or c search paths based on clang args
  src/lib.rs
Labels: S-awaiting-review
